def merge_dicts(*dict_args):
    # Given any number of dicts, shallow copy and merge into a new dict,
    # precedence goes to key value pairs in latter dicts.
    result = {}
    for dictionary in dict_args:
        result.update(dictionary)
    return result


CISCO_VLAN_MEMBERSHIP = '9.9.68.1.2.2.1.2'

exit_status_map = {
    "OK": 0,
    "WARNING": 1,
    "CRITICAL": 2,
    "UNKNOWN": 3
}

iana = (
    "",
    "other",
    "regular1822",
    "hdh1822",
    "ddnX25",
    "rfc877x25",
    "ethernet",
    "",
    "TokenBus",
    "TokenRing",
    "iso88026Man",
    "starLan",
    "proteon10Mbit",
    "proteon80Mbit",
    "hyperchannel",
    "fddi",
    "lapb",
    "sdlc",
    "DSL",
    "E1",
    "basicISDN",
    "primaryISDN",
    "propritory PointToPointSerial",
    "PPP",
    "softwareLoopback",
    "CLNP over IP ",
    "ethernet3Mbit",
    "XNS over IP",
    "SLIP",
    "ultra",
    "DS3",
    "SMDS",
    "frameRelay DTE",
    "RS232",
    "Parallel port",
    "arcnet",
    "arcnetPlus",
    "ATM",
    "miox25",
    "SONET / SDH ",
    "X25PLE",
    "iso88022llc",
    "localTalk",
    "SMDSDxi",
    "frameRelayService",
    "v35",
    "hssi",
    "hippi",
    "Generic MODEM",
    "",
    "sonetPath",
    "sonetVT",
    "SMDSIcip",
    "propVirtual",
    "propMultiplexor",
    "ieee80212 100BaseVG",
    "fibreChannel",
    "HIPPI interface",
    "",
    "ATM Emulated LAN for 802.3",
    "ATM Emulated LAN for 802.5",
    "ATM Emulated circuit          ",
    "",
    "ISDN / X.25           ",
    "CCITT V.11/X.21             ",
    "CCITT V.36                  ",
    "CCITT G703 at 64Kbps",
    "G703 at 2Mb",
    "SNA QLLC ",
    "",
    "channel  ",
    "ieee80211 radio spread spectrum       ",
    "IBM System 360/370 OEMI Channel",
    "IBM Enterprise Systems Connection",
    "Data Link Switching",
    "ISDN S/T interface",
    "ISDN U interface",
    "Link Access Protocol D",
    "IP Switching Objects",
    "Remote Source Route Bridging",
    "ATM Logical Port",
    "Digital Signal Level 0",
    "ds0 Bundle (group of ds0s on the same ds1)",
    "Bisynchronous Protocol",
    "Asynchronous Protocol",
    "Combat Net Radio",
    "ISO 802.5r DTR",
    "Ext Pos Loc Report Sys",
    "Appletalk Remote Access Protocol",
    "Proprietary Connectionless Protocol",
    "CCITT-ITU X.29 PAD Protocol",
    "CCITT-ITU X.3 PAD Facility",
    "frameRelay MPI",
    "CCITT-ITU X213",
    "ADSL",
    "Rate-Adapt. DSL",
    "SDSL",
    "Very High-Speed DSL",
    "ISO 802.5 CRFP",
    "Myricom Myrinet",
    "voiceEM voice recEive and transMit",
    "voiceFXO voice Foreign Exchange Office",
    "voiceFXS voice Foreign Exchange Station",
    "voiceEncap voice encapsulation",
    "VoIP",
    "ATM DXI",
    "ATM FUNI",
    "ATM IMA",
    "PPP Multilink Bundle",
    "IBM ipOverCdlc",
    "IBM Common Link Access to Workstn",
    "IBM stackToStack",
    "IBM VIPA",
    "IBM multi-protocol channel support",
    "IBM IP over ATM",
    "ISO 802.5j Fiber Token Ring",
    "IBM twinaxial data link control",
    "",
    "HDLC",
    "LAP F",
    "V.37",
    "X25 Multi-Link Protocol",
    "X25 Hunt Group",
    "Transp HDLC",
    "Interleave channel",
    "Fast channel",
    "IP (for APPN HPR in IP networks)",
    "CATV Mac Layer",
    "CATV Downstream interface",
    "CATV Upstream interface",
    "Avalon Parallel Processor",
    "Encapsulation interface",
    "Coffee pot (no, really)",
    "Circuit Emulation Service",
    "ATM Sub Interface",
    "Layer 2 Virtual LAN using 802.1Q",
    "Layer 3 Virtual LAN using IP",
    "Layer 3 Virtual LAN using IPX",
    "IP over Power Lines",
    "Multimedia Mail over IP",
    "Dynamic Synchronous Transfer Mode",
    "Data Communications Network",
    "IP Forwarding Interface",
    "Multi-rate Symmetric DSL",
    "IEEE1394 High Performance Serial Bus",
    "HIPPI-6400 ",
    "DVB-RCC MAC Layer",
    "DVB-RCC Downstream Channel",
    "DVB-RCC Upstream Channel",
    "ATM Virtual Interface",
    "MPLS Tunnel Virtual Interface",
    "Spatial Reuse Protocol",
    "Voice Over ATM",
    "Voice Over Frame Relay ",
    "Digital Subscriber Loop over ISDN",
    "Avici Composite Link Interface",
    "SS7 Signaling Link ",
    "Prop. P2P wireless interface",
    "Frame Forward Interface",
    "Multiprotocol over ATM AAL5",
    "USB Interface",
    "IEEE 802.3ad Link Aggregate",
    "BGP Policy Accounting",
    "FRF .16 Multilink Frame Relay ",
    "H323 Gatekeeper",
    "H323 Voice and Video Proxy",
    "MPLS",
    "Multi-frequency signaling link",
    "High Bit-Rate DSL - 2nd generation",
    "Multirate HDSL2",
    "Facility Data Link 4Kbps on a DS1",
    "Packet over SONET/SDH Interface",
    "DVB-ASI Input",
    "DVB-ASI Output ",
    "Power Line Communtications",
    "Non Facility Associated Signaling",
    "TR008",
    "Remote Digital Terminal",
    "Integrated Digital Terminal",
    "ISUP",
    "Cisco proprietary MAC layer",
    "Cisco proprietary Downstream",
    "Cisco proprietary Upstream",
    "HIPERLAN Type 2 Radio Interface",
    "PropBroadbandWirelessAccesspt2multipt",
    "SONET Overhead Channel",
    "Digital Wrapper",
    "ATM adaptation layer 2",
    "MAC layer over radio links",
    "ATM over radio links   ",
    "Inter Machine Trunks",
    "Multiple Virtual Lines DSL",
    "Long Reach DSL",
    "Frame Relay DLCI End Point",
    "ATM VCI End Point",
    "Optical Channel",
    "Optical Transport",
    "Proprietary ATM       ",
    "Voice Over Cable Interface",
    "Infiniband",
    "TE Link",
    "Q.2931",
    "Virtual Trunk Group",
    "SIP Trunk Group",
    "SIP Signaling   ",
    "CATV Upstream Channel",
    "Acorn Econet",
    "FSAN 155Mb Symetrical PON interface",
    "FSAN622Mb Symetrical PON interface",
    "Transparent bridge interface",
    "Interface common to multiple lines",
    "voice E&M Feature Group D",
    "voice FGD Exchange Access North American",
    "voice Direct Inward Dialing",
    "MPEG transport interface",
    "6to4 interface",
    "GTP (GPRS Tunneling Protocol)",
    "Paradyne EtherLoop 1",
    "Paradyne EtherLoop 2",
    "Optical Channel Group",
    "HomePNA ITU-T G.989",
    "Generic Framing Procedure (GFP)",
    "Layer 2 Virtual LAN using Cisco ISL",
    "Acteleis proprietary MetaLOOP High Speed Link ",
    "FCIP Link ",
    "Resilient Packet Ring Interface Type",
    "RF Qam Interface",
    "Link Management Protocol"
)

eth_status = (
    "UNKNOWN",
    "UP",
    "DOWN",
    "TESTING"
    "UNKNOWN",
    "DORMANT",
    "NOT PRESENT",
    "LOWER LAYER DOWN"
)

strg_types = {
    "1.3.6.1.2.1.25.2.1.1": "other",
    "1.3.6.1.2.1.25.2.1.2": "physical",
    "1.3.6.1.2.1.25.2.1.3": "virtual",
    "1.3.6.1.2.1.25.2.1.4": "mount",
    "1.3.6.1.2.1.25.2.1.10": "nfs"
}
